create table wall (
  id serial primary key,
  user varchar(20), 
  clue11 varchar(15) not null, 
  clue12 varchar(15) not null, 
  clue13 varchar(15) not null, 
  clue14 varchar(15) not null, 
  connection1 varchar(30) not null,
  explanation1 varchar(255) not null,
  clue21 varchar(15) not null, 
  clue22 varchar(15) not null, 
  clue23 varchar(15) not null, 
  clue24 varchar(15) not null, 
  connection2 varchar(30) not null,
  explanation2 varchar(255) not null,
  clue31 varchar(15) not null, 
  clue32 varchar(15) not null, 
  clue33 varchar(15) not null, 
  clue34 varchar(15) not null, 
  connection3 varchar(30) not null,
  explanation3 varchar(255) not null,
  clue41 varchar(15) not null, 
  clue42 varchar(15) not null, 
  clue43 varchar(15) not null, 
  clue44 varchar(15) not null, 
  connection4 varchar(30) not null,
  explanation4 varchar(255) not null,
  submit_time timestamp default current_timestamp);

insert into wall (user,
    clue11,
    clue12,
    clue13,
    clue14,
    connection1,
    explanation1,
    clue21,
    clue22,
    clue23,
    clue24,
    connection2,
    explanation2,
    clue31,
    clue32,
    clue33,
    clue34,
    connection3,
    explanation3,
    clue41,
    clue42,
    clue43,
    clue44,
    connection4,
    explanation4) 
values ('jram95','Ginger', 'Crumb', 'Sporty', 'Entwine', 'Hidden alcohols', 'They contain alcoholic beverage names within them','Twist', 'Weave','Tangle','Lace','Synonym for twist', 'They are all synonyms for each other to mean tangle or weave','Mersey','Wye','Dee','Trent','UK rivers','Rivers in the UK','Smith', 'Tennant','Eccleston','Whittaker','Doctor Who actors','Surnames of actors who played Doctor Who');